config/routes.rb
Tweetapp::Application.routes.draw do
 
devise_for :users do

  get "/", :to => "home#index"

end

root :to => "home#index"

  resources :users
    match '/users/followers/:id',:as=>'user_followers' , :controller => 'users', :action => 'followers'  
    match '/users/followed/:id',:as=>'user_followed' , :controller => 'users', :action => 'followed'      

  resources :tweets
  resources :comments

  resources :home

  resources :followers
    match '/followers/:id(.:format)',:as=>'destroy_followed' , :controller => 'followers', :action => 'destroy'      

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :id_user, :tweet_content, :tweet_created, :tweet_status
  belongs_to:user

  validates :tweet_content, presence: true

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new

    @tweet = Tweet.new
    @tweet.id_user = current_user.id   
    @tweet.tweet_status = 'active'
    @tweet.tweet_created = Time.now.strftime("%m/%d/%Y")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
    @tweet.id_user = current_user.id_user
    if @tweet.tweet_created == ''
        @tweet.tweet_created = Time.now.strftime("%m/%d/%Y")            
    end  
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save

        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      redirect_to request.env['HTTP_REFERER']      
    end 

  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--    @tweet.id_user = current_user.id   
    @tweet.tweet_status = 'active'
    @tweet.tweet_created = Time.now.strftime("%m/%d/%Y")  -->
<%= f.text_field :id_user, :type => :hidden %>
<%= f.text_field :tweet_status, :type => :hidden %>
<%= f.text_field :tweet_created, :type => :hidden %>
        <div class="span10 tell contents telldiv input-prepend" style ="float:right">
        <center>
    <%= f.text_field :tweet_content,:class =>"span7 search-query ",:placeholder=>"¿Qué estás pensando?",:autofocus => true  %>

    <a href="" class ="btn btn-success sendbutton"><i class ="icon-ok" ></i></a>
<button type ="reset" class = "btn btn-danger cancelbutton"><i class=" icon-remove-circle"></i></button>
    <a href="<%= home_index_path%>" class ="btn btn-success sendbutton"><i class ="icon-refresh" ></i></a>
      </center>
      </div>
<% end %>

<script type="text/javascript">

    $(document).ready(function(){
        $('#new_tweet').validate({
            errorElement:       'div',
            errorClass:         '',

            rules: {
                tweet:{
                    required:   true,
                    minlength : 3                    
                },


            },
            messages: {
                tweet:{
                    required:   'Value is required and can´t be empty',
                    minlength:  "Must be at least 3 characters long."
                }
            }

        });


});
</script>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Lista Tweets</h1>


<% @tweets.each do |tweet| %>
        <div class="span12 contents userdiv">
          <div class="lft">
            <a href="users/<%= tweet.id_user%>"><img data-src="/assets/holder.js/50x50" class="img-circle" title="User Name" style="width: 50px; height: 50px;" src=""></a>
            
          </div>

          <div class="rgt" style="width:85%;">
              <pre><%= tweet.tweet_content %></pre>
          </div>
        </div>
    <%= #link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } 
    %>
<div class="clearfix"></div>
<% end %>

<br />

app/views/tweets/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tweet status:</b>
  <%= @tweet.tweet_status %>
</p>

<p>
  <b>Tweet content:</b>
  <%= @tweet.tweet_content %>
</p>

<p>
  <b>Tweet created:</b>
  <%= @tweet.tweet_created %>
</p>

<p>
  <b>Id user:</b>
  <%= @tweet.id_user %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>