config/routes.rb
Tweetapp::Application.routes.draw do
 
devise_for :users do

  get "/", :to => "home#index"

end

root :to => "home#index"

  resources :users
    match '/users/followers/:id',:as=>'user_followers' , :controller => 'users', :action => 'followers'  
    match '/users/followed/:id',:as=>'user_followed' , :controller => 'users', :action => 'followed'      

  resources :tweets
  resources :comments

  resources :home

  resources :followers
    match '/followers/:id(.:format)',:as=>'destroy_followed' , :controller => 'followers', :action => 'destroy'      

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :id_user, :user_created, :user_name, :user_status

  has_many:tweets


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  def index
        @seguidos  = Follower.where("id_user = :id_user", {id_user: current_user.id}).count 
        @seguidores =  Follower.where("id_follow = :id_follow", {id_follow: current_user.id}).count
    @followed  = Follower.where("id_user = :id_user", {id_user: current_user.id}) 
    @id_followers = Array.new
    @id_foll = Array.new            
    @followed.each do |f|
       @id_foll.push(f.id)    
      @id_followers.push(f.id_follow)
    end     
    @users = User.all

    
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @followed  = Follower.where("id_user = :id_user", {id_user: current_user.id}) 
    @seguidos  = Follower.where("id_user = :id_user", {id_user: current_user.id}).count 
    @seguidores =  Follower.where("id_follow = :id_follow", {id_follow: current_user.id}).count
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end




  # GET /users/followers/:id
  def followers
        @seguidos  = Follower.where("id_user = :id_user", {id_user: current_user.id}).count 
        @seguidores =  Follower.where("id_follow = :id_follow", {id_follow: current_user.id}).count   
        @followed  = Follower.where("id_user = :id_user", {id_user: current_user.id}) 
            @id_followers = Array.new
            @id_foll = Array.new            
            @followed.each do |f|
              @id_followers.push(f.id_follow)
              @id_foll.push(f.id)              
            end 

        @followers  = Follower.where("id_follow = :id_follow", {id_follow: current_user.id})
        @users = Array.new

        @followers.each do |f|
          user = User.find(f.id_user)
          @users.push(user)

        end
  end
  # GET /users/followed/:id
  def followed
        @seguidos  = Follower.where("id_user = :id_user", {id_user: current_user.id}).count 
        @seguidores =  Follower.where("id_follow = :id_follow", {id_follow: current_user.id}).count       
        @followed  = Follower.where("id_user = :id_user", {id_user: current_user.id})
        @users = Array.new
        @followed.each do |f|
          user = User.find(f.id_follow)
          @users.push(user)

        end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.user_created = Time.now.strftime("%m/%d/%Y")
    @user.user_status = "active"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
        @seguidos  = Follower.where("id_user = :id_user", {id_user: current_user.id}).count 
        @seguidores =  Follower.where("id_follow = :id_follow", {id_follow: current_user.id}).count    
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @seguidos  = Follower.where("id_user = :id_user", {id_user: current_user.id}).count 
    @seguidores =  Follower.where("id_follow = :id_follow", {id_follow: current_user.id}).count
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/finder.html.erb
finder

app/views/users/followed.html.erb
<h1>Seguidos</h1>




<% @users.each do |u| %>

<div class = "span2" style = "float:left">
<center>
<%= link_to raw('<img data-src="/assets/holder.js/120x120" class="img-polaroid" alt="140x140" style="width: 120px; height: 120px;padding:20px;" src="" width="100%">'), user_path(u.id) %>
<div><h4><%= u.user_name %></h4></div>
<div style ="padding-left:25px;">
<%= link_to raw('<i class="icon-user icon-white"></i> '), user_path(u.id), :class=>"btn btn-inverse lft",:style =>"margin-right:10px" %>
<% pos =  %>
<% @followed.each do |f| %>
<%	if (f.id_follow == u.id)%>
<%=	 link_to raw('<i class="icon-ban-circle icon-white"></i> '), destroy_followed_path(f.id), method: :delete,:class=>"btn btn-inverse lft"%> 	
<%	end %>

<% end %>
	
</div>
</center>
 </div>
<% end %>
<br />

app/views/users/followers.html.erb
<h1>Seguidores</h1>




<% @users.each do |u| %>

<div class = "span2" style = "float:left">
<center>
<%= link_to raw('<img data-src="/assets/holder.js/120x120" class="img-polaroid" alt="140x140" style="width: 120px; height: 120px;padding:20px;" src="" width="100%">'), user_path(u.id) %>
<div><h4><%= u.user_name %></h4></div>
<div style ="padding-left:25px;">
<%= link_to raw('<i class="icon-user icon-white"></i> '), user_path(u.id), :class=>"btn btn-inverse lft",:style =>"margin-right:10px" %>

<% count = 0 %>
<% pos = 0 %>
<% followed=false %>
	<% @id_followers.each do | d| %>
		<% count+=1 %>
		<% if u.id==d %>
			<% pos = count %>
			<% followed=true %>	

		<% end %>	

	<% end %>

<% if followed   %>		
	<%= link_to raw('<i class="icon-ban-circle icon-white"></i> '), destroy_followed_path(@id_foll.at(pos-1)), method: :delete,:class=>"btn btn-inverse lft" %>			
<%else%>
	<%= link_to raw('<i class="icon-road icon-white"></i> '), new_follower_path(:follower => {:id_follow => u.id}), :class=>"btn btn-inverse lft" %>	
<% end %>

<br>

</div>
</center>
 </div>
<% end %>
<br />

app/views/users/index.html.erb
<h1>Usuarios</h1>
<%cant_usuarios = 0%>
<% @users.each do |user| %>
<%cant_usuarios +=1%>
<div class = "span2" style = "float:left">
<center>
<%= link_to raw('<img data-src="/assets/holder.js/120x120" class="img-polaroid" alt="140x140" style="width: 120px; height: 120px;padding:20px;" src="" width="100%">'), user_path(current_user.id) %>
<div><h4><%= user.user_name %></h4></div>
<div style ="padding-left:25px;">
<%= link_to raw('<i class="icon-user icon-white"></i> '), user, :class=>"btn btn-inverse lft",:style =>"margin-right:10px" %>

<% count = 0 %>
<% pos = 0 %>
<% followed=false %>
	<% @id_followers.each do | d| %>
		<% count+=1 %>
		<% if user.id==d %>
			<% pos = count %>
			<% followed=true %>	

		<% end %>	

	<% end %>

		<% if followed   %>		
			<%= link_to raw('<i class="icon-ban-circle icon-white"></i> '), destroy_followed_path(@id_foll.at(pos-1)), method: :delete,:class=>"btn btn-inverse lft" %>			
		<%else%>

			<% if current_user.id!=user.id%>
				<%= link_to raw('<i class="icon-road icon-white"></i> '), new_follower_path(:follower => {:id_follow => user.id}), :class=>"btn btn-inverse lft" %>	
			<% end %>
		<% end %>
</div>
</center>
 </div>
	<% if cant_usuarios>=5 %>
	<% cant_usuarios=0 %>
	<div class="clearfix"></div>
	<p></p><br>
	<% end %>
<% end %>


<div class="clearfix"></div>

<%= # link_to 'New User', new_user_path
 %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class = "span8 viewUser">
<center>
	<div class = "resheader" ><h3>Resumen Del Perfil</h3></div>
</center>
<div  style=" border: 1px solid #9C9CA2; padding: 2%;">

<center>


  <img data-src="/assets/holder.js/120x120" class="img-polaroid" alt="140x140" style="width: 120px; height: 120px;padding:20px;"  width="100%">

                       <h4 class="cntr">  <%= @user.user_name %></h4>


                    <div class="clearfix"></div>
<%	followed = false %>
<% @followed.each do |f| %>

	<% if f.id_follow == @user.id%>
			<%= link_to raw('<i class="icon-ban-circle icon-white"></i> '), destroy_followed_path(f.id), method: :delete,:class=>"btn btn-inverse " %>	
			<%	followed = true %>
	<% end %>
<% end %>
		<% if  current_user.id!=@user.id and !followed %>
				<%= link_to raw('<i class="icon-road icon-white"></i> Follow'), new_follower_path(:follower => {:id_follow => @user.id}), :class => 'btn btn-inverse' %>
		<% end  %>
</center> 
<p></p>
<div class="clearfix"></div>
<center>	<table class="table " style = "margin-top: 20px; width: 76%;" >
		<tbody>
			<tr><td><strong>User Name</strong>	</td><td><%= @user.user_name %></td> </tr>
			<tr><td><strong>User email</strong>	</td><td><%= @user.email %></td> </tr>
			<tr><td><strong>User created</strong>	</td><td><%= @user.created_at %></td> </tr>			
			<tr><td><strong>Last sign in</strong>	</td><td><%= @user.last_sign_in_at %></td> </tr>	
		</tbody>
	</table>
</center>
</div>

</div>