config/routes.rb
Tweetapp::Application.routes.draw do
 
devise_for :users do

  get "/", :to => "home#index"

end

root :to => "home#index"

  resources :users
    match '/users/followers/:id',:as=>'user_followers' , :controller => 'users', :action => 'followers'  
    match '/users/followed/:id',:as=>'user_followed' , :controller => 'users', :action => 'followed'      

  resources :tweets
  resources :comments

  resources :home

  resources :followers
    match '/followers/:id(.:format)',:as=>'destroy_followed' , :controller => 'followers', :action => 'destroy'      

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  attr_accessible :id_follow, :id_user
  has_many :users
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followers }
    end
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
    @follower = Follower.find(params[:id])
      redirect_to request.env['REQUEST_URI']      
  end


  # GET /followers/new
  # GET /followers/new.json
  def new
    @follower = Follower.new(params[:follower])
    @follower.id_user = current_user.id 
      if @follower.save
        redirect_to user_path(@follower.id_follow)
      end 
  
  end

  # GET /followers/1/edit
  def edit
    @follower = Follower.find(params[:id])
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(params[:follower])

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render json: @follower, status: :created, location: @follower }
      else
        format.html { render action: "new" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /followers/1
  # PUT /followers/1.json
  def update
    @follower = Follower.find(params[:id])

  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower = Follower.find(params[:id])

    if @follower.destroy
      redirect_to request.env['HTTP_REFERER']      
    end 
  end

end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= @follower.inspect %><br />
  <div class="field">
    <%= f.label :id_follow %><br />
    <%= f.number_field :id_follow %>
  </div>
  
  <div class="field">
    <%= f.number_field :id_user,:type => 'hidden' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<h1>Listing followers</h1>

<table>
  <tr>
    <th>Id</th>

    <th>Id follow</th>
    <th>Id user</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @followers.each do |follower| %>
  <tr>
    <td><%= follower.id %></td>
    <td><%= follower.id_follow %></td>
    <td><%= follower.id_user %></td>
    <td><%= link_to 'Show', follower %></td>
    <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
    <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id follow:</b>
  <%= @follower.id_follow %>
</p>

<p>
  <b>Id user:</b>
  <%= @follower.id_user %>
</p>


<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>